---
title: "Leaflet"
author: "Chandrasekar Ganesan"
date: "September 6, 2017"
output: 
  html_document: 
    self_contained: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Leaflet Exercise

Purpose of this exercise is to draw a map using leaflet and publish it. This exercise will use the zipcode data for illustration purposes.

```{r}
library(leaflet)
library(zipcode)
data(zipcode)
```

>Select 50 random data for plotting (Ignore NA when selecting data)

```{r}

set.seed(09-06-2017)
sampleRows <- sample(nrow(zipcode[complete.cases(zipcode),]),50)
sampleData <- zipcode[sampleRows,]
#
```


## Leaflet Plot
```{r}

getColor <- function(sampleData) {
  sapply(sampleData$zips, function(zip) {
    if (as.numeric(zip) %% 2 == 0) {
      "red"
    } else {
      "green"
    }
  })
}

icons <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'green',
  library = 'ion'
)


m = leaflet(sampleData) %>% addTiles() %>% addAwesomeMarkers(lng = ~longitude, lat = ~latitude, icon = icons, popup = ~paste(city,",",state))

m
```


